account/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views

from .views import activate_user_account, signup, profile, CustomLoginView


app_name = "account"

urlpatterns = [
    re_path(
        r"activate/(?P<signed_user>[0-9A-Za-z_\-]+/[A-Za-z0-9_=-]+/[A-Za-z0-9_=-]+)/$",
        activate_user_account,
        name="activate_user_account",
    ),
    path("signup/", signup, name="signup"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="registration/logout.html"),
        name="logout",
    ),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="registration/password_change.html",
            success_url=reverse_lazy("users:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="registration/password_changed.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/email_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_confirmed.html"
        ),
        name="password_reset_complete",
    ),
    path("profile/", profile, name="profile"),
]

study_language/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls", namespace="account")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/activation.html
{% load static %}
{% autoescape off %}

<html>
<title>Електронна пошта для реєстрації</title>
<body>
<div>
  <span>Зареєструйтесь</span>
</div>
<div class="email-main">
  <p>Шановний користувач</p>
  <p>Ми відправили Вам цей лист, тому що Ви зареєструвалися на нашому веб-сайті.
    Перейдіть по посиланню, щоб підтвердити свою електронну пошту:
  </p>
  <div>
    <a href="{{ activate_url }}">
      Підтвердьте електронну пошту
    </a>
  </div>
  <p>Якщо це були не ви, проігноруйте цей електронний лист.</p>
</div>
</body>
</html>
{% endautoescape %}

templates/base.html
<!doctype  html>
{% load i18n %}
<html  lang="en">
<head>
<link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
<title>{% translate 'Study language' %}</title>
</head>
<body>
  <div  class="container">
    <div  class="row justify-content-center">
      <div  class="col-4">
      <h1  class="text-center">{% translate 'Study language' %}</h1>
      {% block content %}
      {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

templates/email_verify_done.html
{% extends 'base.html' %}

{% block head %}
<title>Адреса електронної пошти підтверджена</title>
{% endblock head %}

{% block content %}
<div class="container justify-content-center  mt-4 pt-4">
    {% if user.is_active %} {% if reuqest.user.is_authenticated %}
    <a class="text-center" href="{% url 'account:profile' %}">Перейти в профіль</a>
    {% else %}
    <p class="text-center">
        Адреса електронної пошти підтверджена<br>
        Ви можете <a href="{% url 'account:login' %}">ввійти</a>
    </p>
    {% endif %} {% else %}
    <p>Щось пішло не так.</p>
    {% endif %}
</div>
{% endblock %}

templates/email_verify_end_of_time.html
{% extends 'base.html' %}

{% block head %}
<title>Підтвердьте свою електронну адресу</title>
{% endblock head %}

{% block content %}
<div class="container justify-content-center mt-4 pt-4">
    <h1 class="text-center">Підтвердіть Вашу електронну адресу</h1>
    <p>Термін дії цього посилання на підтвердження електронної пошти минув або недійсний.
        Ми надіслали Вам електронний лист із новим посиланням. Будь ласка, перевірте свою пошту.</p>
</div>
{% endblock content %}